version: '2.4'
services:
  nwnxee-server:
    container_name: nwnxee-server
    image: nwnxee/unified:latest
    restart: always
    volumes:
      - ./server/:/nwn/home
    ports:
      - "5121:5121/udp"
    stdin_open: true
    tty: true
    environment:
      # nwserver env
      - NWN_MODULE=DockerDemo
      - NWN_SERVERNAME=I was too lazy to configure my server.
      - NWN_PUBLICSERVER=0
      - NWN_MAXCLIENTS=96
      - NWN_MINLEVEL=1
      - NWN_MAXLEVEL=10
      - NWN_PAUSEANDPLAY=0
      - NWN_PVP=2
      - NWN_SERVERVAULT=1
      - NWN_ELC=0
      - NWN_ILR=0
      - NWN_GAMETYPE=0
      - NWN_ONEPARTY=0
      - NWN_DIFFICULTY=3
      - NWN_AUTOSAVEINTERVAL=0
      - NWN_RELOADWHENEMPTY=0
      - NWN_PLAYERPASSWORD=
      - NWN_DMPASSWORD=DorrianIsMyGod
      - NWN_ADMINPASSWORD=DorrianIsMyGod
      - NWN_MAXHP=1
      # nwnx other Settings
      - NWNX_CORE_LOG_LEVEL=6
      # nwnx env
      - NWNX_ADMINISTRATION_SKIP=y
      - NWNX_BEHAVIOURTREE_SKIP=y
      - NWNX_CHAT_SKIP=y
      - NWNX_CREATURE_SKIP=y
      - NWNX_DAMAGE_SKIP=y
      - NWNX_DATA_SKIP=y
      - NWNX_EVENTS_SKIP=y
      - NWNX_JVM_SKIP=y
      - NWNX_LUA_SKIP=n
      - NWNX_METRICS_INFLUXDB_SKIP=n
      - NWNX_OBJECT_SKIP=y
      - NWNX_PLAYER_SKIP=y
      - NWNX_PROFILER_SKIP=n
      - NWNX_REDIS_SKIP=n
      - NWNX_RUBY_SKIP=y
      - NWNX_SQL_SKIP=n
      - NWNX_THREADWATCHDOG_SKIP=y
      - NWNX_TIME_SKIP=y
      - NWNX_TRACKING_SKIP=y
      - NWNX_WEBHOOK_SKIP=y
      - NWNX_TWEAKS_SKIP=n
      # Influxdb 
      - NWNX_METRICS_INFLUXDB_HOST=grafana
      - NWNX_METRICS_INFLUXDB_PORT=8086
      # nwnx_tweaks
      - NWNX_TWEAKS_HIDE_CLASSES_ON_CHAR_LIST=true
      - NWNX_TWEAKS_DISABLE_PAUSE=true
      # Configure sqlDB and stuff
      - NWNX_SQL_TYPE=MYSQL
      - NWNX_SQL_HOST=db
      - NWNX_SQL_ROOT_PASSWORD=password
      - NWNX_SQL_DATABASE=database
      - NWNX_SQL_USERNAME=username
      - NWNX_SQL_PASSWORD=password
      # redis
      - NWNX_REDIS_HOST=redis

    links:
      - "db:db"
      - "redis:redis"
      - "grafana:grafana"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
  db:
    container_name: db
    image: mysql/mysql-server:5.7
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    volumes:
      - ./mysql-db:/docker-entrypoint-initdb.d
    restart: unless-stopped

  redis:
    container_name: redis  
    image: healthcheck/redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis:/data
    restart: unless-stopped

  grafana:
    image: philhawthorne/docker-influxdb-grafana:latest
    container_name: grafana
    volumes:
      - "./metrics/influxdb:/var/lib/influxdb"
      - "./metrics/grafana:/var/lib/grafana"
    ports:
      - "3003:3003"
      - "3004:8083"
      - "8086:8086"
