version: '2.4'
services:
  nwnxee-server:
    container_name: nwnxee-server
    image: nwnxee/unified:latest
    env_file: ./config/nwserver.env
    stdin_open: true
    tty: true
    links:
      - "db:db"
      - "redis:redis"
      - "grafana:grafana"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./server/:/nwn/home
    restart: always
    ports:
      - "5121:5121/udp"
  db:
    container_name: db
    image: mariadb:latest
    env_file: ./config/db.env
    healthcheck:
      # Change <Your password goes here> by what you put on the MYSQL_ROOT_PASSWORD variable on the db.env file.
      # There should be no paces between -p and the value! (I.E: -ppassword is correct!)
      test: ["CMD", "mysqladmin", "-p<Your password goes here>", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
      start_period: 5s
    volumes:
      - mysql-data:/var/lib/mysql:rw
      #- ./mysql-db:/docker-entrypoint-initdb.d         # TODO: Allow users to initialize their data using this.
    restart: unless-stopped
    ports:
      - "3306:3306"
  redis:
    container_name: redis
    image: healthcheck/redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    volumes:
      - ./redis:/data
    restart: unless-stopped
  grafana:
    image: philhawthorne/docker-influxdb-grafana:edge
    container_name: grafana
    volumes:
      - "./metrics/influxdb:/var/lib/influxdb"
      - "./metrics/grafana:/var/lib/grafana"
    ports:
      - "3003:3003"
      - "3004:8083"
      - "8086:8086"
volumes:
  mysql-data:
